### ISSUE TITLE
Yo i cannot install rise media player

### ISSUE THREAD

**Issue by foursplaysroblox** [Rise-Software/Rise-Media-Player#185]
### Description

i found this error code when i installed it from the github page 

### Steps To Reproduce

error (0x800B010A)

### Expected behavior

I expected for it to install normaly and then get to the licence agreement etc.

### Rise Media Player Version

Not Installed

### Windows Version

Windows 11 Home Insider Preview 22H2 Build 1000.25188.1000.0

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/82078139/187027905-f4b319eb-e8d1-462c-a3dd-b2ae793a46a9.png)
 
 translation: The publisher's certificate of this app package cannot be verified. Contact your system administrator or app developer to get a new app package with verified certificates. Root certificate and all instant signature certificates in the app package must be verified (0x800B010A)

**Comment by itsWindows11** [comment]
[Follow these steps](https://github.com/rise-software/rise-media-player#msix-install-instructions) and it should work.

**Comment by foursplaysroblox** [comment]
thank you it works now!
