### ISSUE TITLE
Add file association

### ISSUE THREAD

**Issue by josephbeattie** [Rise-Software/Rise-Media-Player#23]
Add Rise Media Player to open with context menu.

**Comment by itsWindows11** [comment]
Currently working on it...

**Comment by itsWindows11** [comment]
I'm currently working on it... what file extensions should I add apart from MP3?

**Comment by josephbeattie** [comment]
.MP3, .M4A, .WMA, .WAV, .FLAC, .OGG, .AAC, .AIFF (Audio) 

for Video: .MP4, .AVI, .MOV, .ACVHD, .MKV, .FLV
