### ISSUE TITLE
Settings modal top menu bug

### ISSUE THREAD

**Issue by brunobits** [Rise-Software/Rise-Media-Player#42]
## Description
Sometimes when opening the Settings modal the right-side controuls are tilted to the left, leaving a blank space on the right.

## Attachments
![ApplicationFrameHost_5dRC5xkOfz](https://user-images.githubusercontent.com/48385307/139597109-d325d335-9502-45cb-ab8c-c9bb3f27d091.png)
![fplMhLGORJ](https://user-images.githubusercontent.com/48385307/139597158-df4808c2-e965-4a9a-ba58-7460dc64fa61.gif)

**Comment by josephbeattie** [comment]
We'll have a look :)

**Comment by brunobits** [comment]
It seems to be a modal size bug in general, check the .gif I just uploaded.

**Comment by itsWindows11** [comment]
What if you used a two-column `Grid` for this?

**Comment by YourOrdinaryCat** [comment]
The titlebar has to be the way it is to allow items like the search bar to register clicks/taps, settings already uses a grid but looks like it's kinde broken atm
