### ISSUE TITLE
Removing (and sometimes adding) folders causes the application to crash

### ISSUE THREAD

**Issue by brunobits** [Rise-Software/Rise-Media-Player#43]
## Description
Title.

## Attachments
![LO1mi7uipt](https://user-images.githubusercontent.com/48385307/139597261-8c996891-c190-4040-9052-5dbbc6500be7.gif)

**Comment by sametaor** [comment]
+1

**Comment by Jathurshan-2019** [comment]
This app is in preview now so sometimes it may have bugs and errors.

**Comment by YourOrdinaryCat** [comment]
This will be improved progressively as we figure out indexing - thanks for the feedback!

**Comment by josephbeattie** [comment]
It’s being fixed currently :)
