### ISSUE TITLE
At a glance loading animation

### ISSUE THREAD

**Issue by Muckstern** [Rise-Software/Rise-Media-Player#47]
Loading animation when you open the app shows the windows 10 instead of the line one that windows 11 uses.

**Comment by YourOrdinaryCat** [comment]
Which animation exactly? Got any screenshots/recordings? Is it the splash screen?

**Comment by prakharb5** [comment]
I think @Muckstern meant this - 
![image](https://user-images.githubusercontent.com/51435948/141247543-252f3577-1a83-4fa3-a741-729d121841c7.png)

**Comment by itsWindows11** [comment]
> I think @Muckstern meant this - ![image](https://user-images.githubusercontent.com/51435948/141247543-252f3577-1a83-4fa3-a741-729d121841c7.png)

This will be fixed when Pre Alpha 4 releases, which contains the new now playing bar, it won't have this loading animation.

**Comment by esibruti** [comment]
@itsWindows11 Fixed issue with Pre-Alpha 4 release
