### ISSUE TITLE
can't install the Msixbundle due to untrusted certificate

### ISSUE THREAD

**Issue by AthoyeMahmud** [Rise-Software/Rise-Media-Player#49]
below is my powershell terminal output;

`PS C:\Users\Athoye> add-appxpackage -Path "D:\Packages\RiseMP_v0.0.11.0.msixbundle"                                     add-appxpackage : Deployment failed with HRESULT: 0x800B0109, A certificate chain processed, but terminated in a root
certificate which is not trusted by the trust provider.
error 0x800B0109: The root certificate of the signature in the app package or bundle must be trusted.
NOTE: For additional information, look for [ActivityId] e36ddd5e-d3af-0000-c684-b6e3afd3d701 in the Event Log or use
the command line Get-AppPackageLog -ActivityID e36ddd5e-d3af-0000-c684-b6e3afd3d701
At line:1 char:1
+ add-appxpackage -Path "D:\Packages\RiseMP_v0.0.11.0.msixbundle"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (D:\Packages\RiseMP_v0.0.11.0.msixbundle:String) [Add-AppxPackage], Except
   ion
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

PS C:\Users\Athoye>`

**Comment by itsWindows11** [comment]
Have you tried following the instructions at readme?
